/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Igniter
 */
public class ViewDatos extends javax.swing.JFrame {

    /**
     * Creates new form ViewDatos
     */
    public ViewDatos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOrdenar = new javax.swing.JMenu();
        jMenuNombre = new javax.swing.JMenuItem();
        jMenuPromedio = new javax.swing.JMenuItem();
        jMenuProfesion = new javax.swing.JMenuItem();
        jMenuFiltrar = new javax.swing.JMenu();
        jMenuFiltrarNombre = new javax.swing.JMenuItem();
        jMenuFiltrarPrormedio = new javax.swing.JMenuItem();
        jMenuFiltrarProfesion = new javax.swing.JMenuItem();
        jMenuFiltrarNombrePromedio = new javax.swing.JMenuItem();
        jMenuFiltrarNombreProfesion = new javax.swing.JMenuItem();
        jMenuFiltrarPromedioProfesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Listado de egresados");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        MenuOrdenar.setText("Ordenar");

        jMenuNombre.setText("Nombre");
        MenuOrdenar.add(jMenuNombre);

        jMenuPromedio.setText("Promedio");
        MenuOrdenar.add(jMenuPromedio);

        jMenuProfesion.setText("Profesion");
        MenuOrdenar.add(jMenuProfesion);

        jMenuBar1.add(MenuOrdenar);

        jMenuFiltrar.setText("Filtrar");

        jMenuFiltrarNombre.setText("Nombre");
        jMenuFiltrarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFiltrarNombreMouseClicked(evt);
            }
        });
        jMenuFiltrarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFiltrarNombreActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(jMenuFiltrarNombre);

        jMenuFiltrarPrormedio.setText("Promedio");
        jMenuFiltrarPrormedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFiltrarPrormedioActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(jMenuFiltrarPrormedio);

        jMenuFiltrarProfesion.setText("Profesion");
        jMenuFiltrarProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFiltrarProfesionActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(jMenuFiltrarProfesion);

        jMenuFiltrarNombrePromedio.setText("Nombre y Promedio");
        jMenuFiltrarNombrePromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFiltrarNombrePromedioActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(jMenuFiltrarNombrePromedio);

        jMenuFiltrarNombreProfesion.setText("Nombre y Profesion");
        jMenuFiltrarNombreProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFiltrarNombreProfesionActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(jMenuFiltrarNombreProfesion);

        jMenuFiltrarPromedioProfesion.setText("Promedio y Profesion");
        jMenuFiltrarPromedioProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFiltrarPromedioProfesionActionPerformed(evt);
            }
        });
        jMenuFiltrar.add(jMenuFiltrarPromedioProfesion);

        jMenuBar1.add(jMenuFiltrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFiltrarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFiltrarNombreMouseClicked
        // TODO add your handling code here:
        new ViewBusquedaNombre().setVisible(true);
    }//GEN-LAST:event_jMenuFiltrarNombreMouseClicked

    private void jMenuFiltrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFiltrarNombreActionPerformed
        new ViewBusquedaNombre().setVisible(true);
        
    }//GEN-LAST:event_jMenuFiltrarNombreActionPerformed

    private void jMenuFiltrarPrormedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFiltrarPrormedioActionPerformed
        // TODO add your handling code here:
        new ViewBusquedaPromedio().setVisible(true);
        
    }//GEN-LAST:event_jMenuFiltrarPrormedioActionPerformed

    private void jMenuFiltrarProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFiltrarProfesionActionPerformed
        // TODO add your handling code here:
        new ViewBusquedaProfesion().setVisible(true);
        
    }//GEN-LAST:event_jMenuFiltrarProfesionActionPerformed

    private void jMenuFiltrarNombrePromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFiltrarNombrePromedioActionPerformed
        // TODO add your handling code here:
        new ViewBusquedaNombrePromedio().setVisible(true);
    }//GEN-LAST:event_jMenuFiltrarNombrePromedioActionPerformed

    private void jMenuFiltrarNombreProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFiltrarNombreProfesionActionPerformed
        // TODO add your handling code here:
        new ViewBusquedaNombreProfesion().setVisible(true);
    }//GEN-LAST:event_jMenuFiltrarNombreProfesionActionPerformed

    private void jMenuFiltrarPromedioProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFiltrarPromedioProfesionActionPerformed
        // TODO add your handling code here:
        new ViewBusquedaPromedioProfesion().setVisible(true);
    }//GEN-LAST:event_jMenuFiltrarPromedioProfesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFiltrar;
    private javax.swing.JMenuItem jMenuFiltrarNombre;
    private javax.swing.JMenuItem jMenuFiltrarNombreProfesion;
    private javax.swing.JMenuItem jMenuFiltrarNombrePromedio;
    private javax.swing.JMenuItem jMenuFiltrarProfesion;
    private javax.swing.JMenuItem jMenuFiltrarPromedioProfesion;
    private javax.swing.JMenuItem jMenuFiltrarPrormedio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuNombre;
    private javax.swing.JMenuItem jMenuProfesion;
    private javax.swing.JMenuItem jMenuPromedio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
